const SUPABASE_URL='https://scrbdfwpthsylmhtqjeu.supabase.co',SUPABASE_KEY='sb_publishable_AezQqW-5YRH2wF69ePpalw_sdmMJvgQ',API=`${SUPABASE_URL}/functions/v1/blue-os7-autopilot`;
const client=supabase.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,detectSessionInUrl:true,autoRefreshToken:true}});let data=null,outcomeQuote=null;
const $=x=>document.getElementById(x),esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const money=v=>new Intl.NumberFormat(undefined,{style:'currency',currency:'USD',maximumFractionDigits:0}).format(Number(v||0));const dt=v=>v?new Date(v).toLocaleDateString():'—';
async function sess(){return (await client.auth.getSession()).data.session}async function api(method='GET',body){const s=await sess();if(!s)throw new Error('Sign in required');const o={method,headers:{Authorization:`Bearer ${s.access_token}`,apikey:SUPABASE_KEY,Accept:'application/json'}};if(body){o.headers['Content-Type']='application/json';o.body=JSON.stringify(body)}const r=await fetch(API,o);const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'Request failed');return j}
function notice(t,bad=false){$('os7Status').textContent=t;$('os7Status').style.color=bad?'#a12f2f':'#24577f'}
async function load(){try{notice('Refreshing OS 7…');data=await api();$('login').classList.add('os6-hide');$('app').classList.remove('os6-hide');$('ownerLine').textContent=`${data.user?.name||''} • ${data.user?.role||''}`;render();notice('Sales + profit intelligence refreshed.')}catch(e){$('app').classList.add('os6-hide');$('login').classList.remove('os6-hide');$('loginMsg').textContent=e.message}}
function render(){const m=data.metrics||{};[['mCustomers',m.customers],['mMargin',money(m.total_gross_margin)],['mRepeat',m.repeat_due],['mCalls',m.hot_calls],['mOutcomes',m.tracked_outcomes],['mCarriers',m.active_rate_sources]].forEach(([i,v])=>$(i).textContent=v??0);renderCalls();renderRepeat();renderProfit();renderBrokers();renderCarriers();renderTasks();renderOutcomes();renderQuotes()}
function renderCalls(){const q=$('callSearch').value.toLowerCase();const rows=(data.call_list||[]).filter(x=>!q||`${x.company_name} ${x.assigned_to||''} ${x.call_reason}`.toLowerCase().includes(q)).slice(0,60);$('callList').innerHTML=rows.length?rows.map(x=>`<div class="os6-row os7-call"><div class="os7-score">${x.call_score}</div><div><strong>${esc(x.company_name)}</strong><div class="os7-reason">${esc(x.call_reason)} • ${esc(x.assigned_to||'Unassigned')}${x.phone?` • ${esc(x.phone)}`:''}${x.estimated_monthly_value?` • est. ${money(x.estimated_monthly_value)}/mo`:''}</div></div><span class="os7-pill ${x.call_score>=90?'high':''}">${x.call_score>=90?'CALL NOW':x.call_score>=80?'HOT':'PRIORITY'}</span></div>`).join(''):'<div class="os6-empty">No matching accounts.</div>'}
function renderRepeat(){$('repeatList').innerHTML=(data.repeat_opportunities||[]).filter(x=>x.opportunity_status!=='future').slice(0,40).map(x=>`<div class="os6-row"><div class="os6-row-top"><strong>${esc(x.company_name)}</strong><span class="os7-pill ${esc(x.opportunity_status)}">${esc(x.opportunity_status).toUpperCase()}</span></div><small>${esc(x.origin||'Origin')} → ${esc(x.destination||'Destination')}${x.equipment_type?` • ${esc(x.equipment_type)}`:''}<br>${x.avg_days_between?`Avg cadence ${x.avg_days_between} days • `:''}Predicted ${esc(dt(x.predicted_next_ship_at))}</small></div>`).join('')||'<div class="os6-empty">Not enough repeat-shipment history yet.</div>'}
function renderProfit(){const rows=(data.profitability||[]).filter(x=>Number(x.quote_count)>0).slice(0,60);$('profitList').innerHTML=rows.length?rows.map(x=>`<div class="os6-row os7-profit"><div><strong>${esc(x.company_name)}</strong><small>${x.quote_count} quotes • ${x.won_quotes} won</small></div><div><small>Quoted</small><strong>${money(x.quoted_revenue)}</strong></div><div><small>Carrier</small><strong>${money(x.quoted_carrier_cost)}</strong></div><div><small>Margin</small><strong>${money(x.gross_margin)}</strong></div><div><small>Margin %</small><strong>${x.margin_pct??'—'}%</strong></div><div><small>Last quote</small><strong>${esc(dt(x.last_quote_at))}</strong></div></div>`).join(''):'<div class="os6-empty">No structured margin history yet.</div>'}
function renderBrokers(){$('brokerBody').innerHTML=(data.brokers||[]).map((x,i)=>`<tr><td>#${i+1}</td><td>${esc(x.name)}</td><td>${x.quote_count}</td><td>${x.wins}</td><td>${x.win_rate_pct}%</td><td>${money(x.gross_margin)}</td><td>${x.week_quotes}</td><td>${money(x.week_margin)}</td></tr>`).join('')}
function renderCarriers(){$('carrierBody').innerHTML=(data.carrier_scorecards||[]).slice(0,75).map(x=>`<tr><td>${esc(x.name)}</td><td>${esc(x.source_type)}</td><td>${x.requests}</td><td>${x.responses}</td><td>${x.response_rate_pct??'—'}%</td><td>${x.avg_response_minutes??'—'}</td><td>${money(x.avg_carrier_cost)}</td><td>${esc(x.network_tier||'—')}</td></tr>`).join('')}
function renderTasks(){$('taskList').innerHTML=(data.autopilot_tasks||[]).map(x=>`<div class="os6-row"><div class="os6-row-top"><strong>${esc(x.title)}</strong><span class="os7-pill ${/high/i.test(x.priority||'')?'high':''}">${esc(x.priority||'normal')}</span></div><small>${esc(x.task_type)} • Due ${esc(dt(x.due_at))}<br>${esc((x.description||'').split('\n').slice(1).join(' '))}</small></div>`).join('')||'<div class="os6-empty">No open OS 7 autopilot tasks.</div>'}
function renderOutcomes(){$('outcomeList').innerHTML=(data.outcomes||[]).slice(0,40).map(x=>{const q=x.quote_margin_records||{};return `<div class="os6-row"><div class="os6-row-top"><strong>${esc(q.quote_number||'Quote')} • ${esc(x.outcome)}</strong><span class="os7-pill">${esc(x.reason||'No reason')}</span></div><small>${esc(`${q.origin_city||''}, ${q.origin_state||''} → ${q.destination_city||''}, ${q.destination_state||''}`)}${x.competitor?` • Competitor: ${esc(x.competitor)}`:''}</small></div>`}).join('')||'<div class="os6-empty">No win/loss reasons recorded yet.</div>'}
function renderQuotes(){$('quoteBody').innerHTML=(data.recent_quotes||[]).slice(0,60).map(x=>`<tr><td>${esc(x.quote_number||'—')}</td><td>${esc(`${x.origin_city||''}, ${x.origin_state||''}`)} → ${esc(`${x.destination_city||''}, ${x.destination_state||''}`)}</td><td>${money(x.customer_rate)}</td><td>${money(x.carrier_cost)}</td><td>${money(x.gross_margin_dollars)}</td><td>${esc(x.status)}</td><td><button class="os6-btn secondary" data-outcome="${esc(x.id)}">Record Outcome</button></td></tr>`).join('');document.querySelectorAll('[data-outcome]').forEach(b=>b.onclick=()=>openOutcome(b.dataset.outcome))}
function openOutcome(id){outcomeQuote=id;$('outcomeModal').classList.add('open');$('outcomeForm').reset()}function closeOutcome(){$('outcomeModal').classList.remove('open');outcomeQuote=null}
async function saveOutcome(e){e.preventDefault();const f=e.currentTarget,b=f.querySelector('button[type=submit]'),fd=Object.fromEntries(new FormData(f));b.disabled=true;b.textContent='Saving…';try{await api('POST',{action:'record_outcome',quote_margin_record_id:outcomeQuote,...fd});closeOutcome();await load();notice('Quote outcome saved.')}catch(err){notice(err.message,true)}finally{b.disabled=false;b.textContent='Save Outcome'}}
async function sweep(){const b=$('runSweep'),old=b.textContent;b.disabled=true;b.textContent='Running…';try{const r=await api('POST',{action:'sweep'});notice(`OS 7 sweep complete — ${r.created||0} new CRM tasks created.`);await load()}catch(e){notice(e.message,true)}finally{b.disabled=false;b.textContent=old}}
$('loginForm').onsubmit=async e=>{e.preventDefault();try{const email=$('email').value.trim();const{error}=await client.auth.signInWithOtp({email,options:{emailRedirectTo:`${location.origin}/owner-os7.html`,shouldCreateUser:false}});if(error)throw error;$('loginMsg').textContent='Secure sign-in link sent. Open it from this device.'}catch(err){$('loginMsg').textContent=err.message}};$('logout').onclick=async()=>{await client.auth.signOut();location.reload()};$('refresh').onclick=load;$('runSweep').onclick=sweep;$('callSearch').oninput=renderCalls;$('outcomeForm').onsubmit=saveOutcome;$('closeOutcome').onclick=closeOutcome;$('cancelOutcome').onclick=closeOutcome;document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.os6-panel').forEach(p=>p.classList.toggle('active',p.id===`panel-${b.dataset.tab}`))});client.auth.onAuthStateChange((e,s)=>{if(e==='SIGNED_IN'&&s)load()});(async()=>{if(await sess())load()})();