const SUPABASE_URL='https://scrbdfwpthsylmhtqjeu.supabase.co',SUPABASE_KEY='sb_publishable_AezQqW-5YRH2wF69ePpalw_sdmMJvgQ',API=`${SUPABASE_URL}/functions/v1/blue-os6-intelligence`;
const client=supabase.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,detectSessionInUrl:true,autoRefreshToken:true}});let data=null;
const $=x=>document.getElementById(x),esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const money=v=>new Intl.NumberFormat(undefined,{style:'currency',currency:'USD',maximumFractionDigits:0}).format(Number(v||0));const dt=v=>v?new Date(v).toLocaleString():'—';
async function sess(){return (await client.auth.getSession()).data.session}async function api(method='GET',body){const s=await sess();if(!s)throw new Error('Sign in required');const o={method,headers:{Authorization:`Bearer ${s.access_token}`,apikey:SUPABASE_KEY,Accept:'application/json'}};if(body){o.headers['Content-Type']='application/json';o.body=JSON.stringify(body)}const r=await fetch(API,o);const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'Request failed');return j}
function notice(t,bad=false){$('os6Status').textContent=t;$('os6Status').style.color=bad?'#9d2d2d':'#24577f'}
async function load(){try{notice('Refreshing intelligence…');data=await api();$('login').classList.add('os6-hide');$('app').classList.remove('os6-hide');$('ownerLine').textContent=`${data.user?.name||''} • ${data.user?.role||''}`;render();notice('Live data refreshed.')}catch(e){$('app').classList.add('os6-hide');$('login').classList.remove('os6-hide');notice(e.message,true)}}
function render(){const m=data.metrics||{};[['mActive',m.active_shipments],['mExceptions',m.exceptions],['mQuotes',m.quotes_30d],['mWin',`${m.quote_win_rate||0}%`],['mRevenue',money(m.visible_shipment_revenue)],['mTasks',m.open_tasks]].forEach(([id,v])=>$(id).textContent=v??0);renderHealth();renderTasks();renderMargin();renderLanes();renderExceptions();renderQuotes()}
function healthClass(s){return /grow|active/i.test(s)?'good':/risk/i.test(s)?'bad':/cool/i.test(s)?'warn':''}
function renderHealth(){const q=$('healthSearch').value.toLowerCase(),rows=(data.customer_health||[]).filter(x=>!q||`${x.company_name} ${x.assigned_to||''} ${x.health_status}`.toLowerCase().includes(q));$('healthList').innerHTML=rows.length?rows.map(x=>`<div class="os6-row os6-health"><div><strong>${esc(x.company_name)}</strong><small>${esc(x.assigned_to||'Unassigned')} • ${x.shipments_30d} shipments / ${x.quotes_30d} quotes in 30d • ${money(x.visible_revenue)}</small></div><div class="os6-score">${x.health_score}</div><span class="os6-pill ${healthClass(x.health_status)}">${esc(x.health_status)}</span></div>`).join(''):'<div class="os6-empty">No matching customers.</div>'}
function renderTasks(){$('taskList').innerHTML=(data.tasks||[]).slice(0,30).map(x=>`<div class="os6-row"><div class="os6-row-top"><strong>${esc(x.title)}</strong><span class="os6-pill ${/high|urgent/i.test(x.priority||'')?'bad':''}">${esc(x.priority||'Normal')}</span></div><small>${esc(x.task_type||'Task')} • Due ${esc(dt(x.due_at))}<br>${esc(x.description||'')}</small></div>`).join('')||'<div class="os6-empty">No open tasks.</div>'}
function renderMargin(){$('marginList').innerHTML=(data.margin_watch||[]).map(x=>`<div class="os6-row"><div class="os6-row-top"><strong>${esc(x.quote_number||'Quote')} · ${esc(x.origin||'')} → ${esc(x.destination||'')}</strong><span class="os6-pill ${/negative|thin/i.test(x.margin_flag)?'bad':'warn'}">${esc(x.margin_flag)}</span></div><small>Sell ${money(x.customer_rate)} • Buy ${money(x.carrier_cost)} • Margin ${money(x.margin_dollars)}${x.margin_pct!=null?` (${x.margin_pct}%)`:''}</small></div>`).join('')||'<div class="os6-empty">No margin warnings.</div>'}
function renderLanes(){$('laneBody').innerHTML=(data.lane_intelligence||[]).map(x=>`<tr><td>${esc(`${x.origin_city||''}, ${x.origin_state||''}`)}</td><td>${esc(`${x.destination_city||''}, ${x.destination_state||''}`)}</td><td>${esc(x.equipment_type)}</td><td>${x.quote_count}</td><td>${money(x.avg_customer_rate)}</td><td>${money(x.avg_carrier_cost)}</td><td>${money(x.avg_margin_dollars)}</td><td>${x.avg_margin_pct??'—'}%</td></tr>`).join('')}
function renderExceptions(){$('exceptionList').innerHTML=(data.exceptions||[]).map(x=>`<div class="os6-row"><div class="os6-row-top"><strong>${esc(x.reference_number)} · ${esc(x.origin)} → ${esc(x.destination)}</strong><span class="os6-pill bad">${esc(x.status)}</span></div><small>${esc(x.exception_note||'Exception flagged')} • Delivery ${esc(dt(x.delivery_scheduled_at))}</small></div>`).join('')||'<div class="os6-empty">No active shipment exceptions.</div>'}
function renderQuotes(){$('quoteBody').innerHTML=(data.quotes||[]).map(x=>`<tr><td>${esc(x.quote_number||'—')}</td><td>${esc(x.origin||'—')} → ${esc(x.destination||'—')}</td><td>${money(x.customer_rate)}</td><td>${money(x.carrier_cost)}</td><td>${esc(x.status||'—')}</td><td><button class="os6-btn secondary" data-convert="${esc(x.id)}">Convert to Shipment</button></td></tr>`).join('');document.querySelectorAll('[data-convert]').forEach(b=>b.onclick=()=>convertQuote(b.dataset.convert,b))}
async function convertQuote(id,b){if(!confirm('Create a shipment from this quote?'))return;const old=b.textContent;b.disabled=true;b.textContent='Creating…';try{const r=await api('POST',{action:'convert_quote',quote_id:id});alert(r.existing?`Shipment already exists: ${r.shipment.reference_number}`:`Shipment created: ${r.shipment.reference_number}`);await load()}catch(e){alert(e.message)}finally{b.disabled=false;b.textContent=old}}
async function refreshTasks(){const b=$('refreshTasks'),old=b.textContent;b.disabled=true;b.textContent='Running…';try{const r=await api('POST',{action:'refresh_tasks'});notice(`Automation sweep complete. ${r.created||0} new CRM tasks created.`);await load()}catch(e){notice(e.message,true)}finally{b.disabled=false;b.textContent=old}}
async function carrierMatch(ev){ev.preventDefault();const f=ev.currentTarget,b=f.querySelector('button');b.disabled=true;b.textContent='Matching…';try{const r=await api('POST',{action:'carrier_matches',origin:f.origin.value,destination:f.destination.value,equipment_type:f.equipment.value});$('carrierList').innerHTML=(r.matches||[]).map(x=>`<div class="os6-row"><div class="os6-row-top"><strong>${esc(x.name)}</strong><span class="os6-pill good">Score ${x.score}</span></div><small>${esc(x.source_type)} • ${esc(x.city||'')}${x.state?`, ${esc(x.state)}`:''} • ${esc(x.authority_status)}<br>${x.response_count} prior responses${x.avg_response_minutes!=null?` • avg ${x.avg_response_minutes} min`:''}${x.avg_carrier_cost!=null?` • avg cost ${money(x.avg_carrier_cost)}`:''}<br>${esc(x.best_for||x.region_focus||'')}</small></div>`).join('')||'<div class="os6-empty">No matches found.</div>'}catch(e){$('carrierList').innerHTML=`<div class="os6-empty">${esc(e.message)}</div>`}finally{b.disabled=false;b.textContent='Find Best Rate Sources'}}
$('loginForm').onsubmit=async e=>{e.preventDefault();const email=$('email').value.trim();try{const{error}=await client.auth.signInWithOtp({email,options:{emailRedirectTo:`${location.origin}/owner-os6.html`,shouldCreateUser:false}});if(error)throw error;$('loginMsg').textContent='Secure sign-in link sent. Open it from this device.'}catch(err){$('loginMsg').textContent=err.message}};$('logout').onclick=async()=>{await client.auth.signOut();location.reload()};$('refresh').onclick=load;$('refreshTasks').onclick=refreshTasks;$('healthSearch').oninput=renderHealth;$('carrierForm').onsubmit=carrierMatch;document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.os6-panel').forEach(p=>p.classList.toggle('active',p.id===`panel-${b.dataset.tab}`))});client.auth.onAuthStateChange((e,s)=>{if(e==='SIGNED_IN'&&s)load()});(async()=>{if(await sess())load()})();