(()=>{
 const API='https://scrbdfwpthsylmhtqjeu.supabase.co/functions/v1/customer-portal-collab';let collab={messages:[],claims:[]},selectedThread=null;
 const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
 const cid=()=>currentCompany||portalData?.companies?.[0]?.id||null;
 const sess=async()=>{const{data}=await client.auth.getSession();return data.session};
 async function api(method='GET',body=null,action='overview'){const s=await sess();if(!s)throw new Error('Sign in required');const u=new URL(API);u.searchParams.set('action',action);const o={method,headers:{Authorization:`Bearer ${s.access_token}`,apikey:SUPABASE_KEY,Accept:'application/json'}};if(body){o.headers['Content-Type']='application/json';o.body=JSON.stringify(body)}const r=await fetch(u,o);const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Unable to complete request');return d}
 const toast=(m,e=false)=>{let t=document.querySelector('.myblue-toast');if(!t){t=document.createElement('div');t.className='myblue-toast';document.body.appendChild(t)}t.textContent=m;t.classList.toggle('error',e);clearTimeout(t._m);t._m=setTimeout(()=>t.remove(),4000)};
 function shell(){const app=document.getElementById('portalApp');if(!app||document.getElementById('myBlue3'))return;const s=document.createElement('section');s.id='myBlue3';s.className='myblue3';s.innerHTML=`<div class="myblue3-grid"><section class="myblue3-card"><span class="portal-kicker">UPCOMING PICKUPS</span><h3>What is moving next</h3><p>Your scheduled freight in one quick view.</p><div id="mb3Upcoming" class="upcoming-list"></div></section><section class="myblue3-card"><span class="portal-kicker">CUSTOMER UPLOADS</span><h3>Send freight documents securely</h3><p>Upload BOLs, packing lists, photos or shipment documents directly to your account.</p><form id="mb3UploadForm" class="myblue3-form"><label>Shipment<select id="mb3UploadShipment" name="shipment_id"><option value="">General account document</option></select></label><label>Document type<select name="document_type"><option>Customer Upload</option><option>BOL</option><option>Packing List</option><option>Shipment Photo</option><option>Other</option></select></label><label class="upload-zone">Choose file<input required type="file" name="file" accept=".pdf,.jpg,.jpeg,.png,.webp,.doc,.docx,.csv,.xlsx"></label><button class="btn primary" type="submit">Upload Securely →</button><div id="mb3UploadStatus" class="portal-upload-status"></div></form></section></div>
 <div class="myblue3-grid"><section class="myblue3-card"><span class="portal-kicker">SHIPMENT MESSAGES</span><h3>Keep freight conversations together</h3><p>Reply inside an existing shipment-help request instead of starting another email chain.</p><div id="mb3Threads" class="thread-list"></div><div id="mb3Messages" class="message-box"><div class="myblue3-empty">Choose a support request to open its conversation.</div></div><form id="mb3MessageForm" class="myblue3-form"><textarea name="message" rows="3" placeholder="Write an update or question..." disabled></textarea><button class="btn primary" type="submit" disabled>Send Message →</button></form></section><section class="myblue3-card"><span class="portal-kicker">CLAIMS & ISSUES</span><h3>Start a damage or shortage claim</h3><p>Submit the basics now and attach supporting files right after.</p><form id="mb3ClaimForm" class="myblue3-form"><label>Shipment<select required name="shipment_id" id="mb3ClaimShipment"></select></label><label>Claim type<select name="claim_type"><option>Damage / Shortage</option><option>Damage</option><option>Shortage</option><option>Loss</option><option>Other</option></select></label><label>Amount claimed <small>Optional</small><input name="amount_claimed" type="number" min="0" step="0.01"></label><label>What happened?<textarea required name="description" rows="4"></textarea></label><label class="upload-zone">Supporting file <small>Optional, 10 MB max</small><input type="file" name="file" accept=".pdf,.jpg,.jpeg,.png,.webp,.doc,.docx"></label><button class="btn primary" type="submit">Submit Claim →</button></form><div id="mb3Claims" class="claim-list"></div></section></div>
 <section class="myblue3-card"><span class="portal-kicker">CSV MULTI-LANE IMPORT</span><h3>Have a lane sheet already?</h3><p>Upload a CSV with headers like <b>origin, destination, equipment, commodity, weight, pickup</b>. We’ll load the rows into your existing Multi-Lane Quote tool for review before submission.</p><div class="csv-box"><input id="mb3Csv" type="file" accept=".csv,text/csv"><button id="mb3CsvLoad" class="portal-ghost" type="button">Load CSV Into Multi-Lane Quote</button><span id="mb3CsvStatus" class="portal-upload-status"></span></div></section>`;const lower=app.querySelector('.portal-lower-grid');(lower||app).insertAdjacentElement(lower?'beforebegin':'beforeend',s);document.getElementById('mb3UploadForm').addEventListener('submit',uploadDoc);document.getElementById('mb3MessageForm').addEventListener('submit',sendMessage);document.getElementById('mb3ClaimForm').addEventListener('submit',submitClaim);document.getElementById('mb3CsvLoad').addEventListener('click',loadCsv);render();}
 function shipments(){return typeof companyShipments==='function'?companyShipments():[]}
 function support(){return window.phase2?.support?.filter?.(x=>x.company_id===cid())||[]}
 function fillShipments(){const opts=shipments().map(x=>`<option value="${esc(x.id)}">${esc(x.reference_number)} · ${esc(x.origin)} → ${esc(x.destination)}</option>`).join('');const u=document.getElementById('mb3UploadShipment');if(u)u.innerHTML='<option value="">General account document</option>'+opts;const c=document.getElementById('mb3ClaimShipment');if(c)c.innerHTML='<option value="">Choose shipment</option>'+opts;}
 function renderUpcoming(){const box=document.getElementById('mb3Upcoming');if(!box)return;const now=Date.now(),next=shipments().filter(x=>x.pickup_scheduled_at&&!x.picked_up_at&&!/deliver|cancel/i.test(x.status||'')).sort((a,b)=>new Date(a.pickup_scheduled_at)-new Date(b.pickup_scheduled_at)).filter(x=>new Date(x.pickup_scheduled_at).getTime()>now-86400000).slice(0,8);box.innerHTML=next.length?next.map(x=>`<article class="upcoming-item"><strong>${esc(x.reference_number)} · ${esc(x.origin)} → ${esc(x.destination)}</strong><small>Pickup ${esc(new Date(x.pickup_scheduled_at).toLocaleString())} • ${esc(x.equipment_type||'Equipment pending')} • ${esc(x.status||'Scheduled')}</small></article>`).join(''):'<div class="myblue3-empty">No upcoming pickups are currently scheduled in the portal.</div>'}
 function renderThreads(){const box=document.getElementById('mb3Threads');if(!box)return;const rows=support();box.innerHTML=rows.length?rows.map(x=>`<article class="thread-item ${selectedThread===x.id?'active':''}" data-thread="${esc(x.id)}"><strong>${esc(x.subject||x.request_type)}</strong><small>${esc(x.status)} • ${esc(x.priority)}</small></article>`).join(''):'<div class="myblue3-empty">Create a Shipment Help request first to start a message thread.</div>';box.querySelectorAll('[data-thread]').forEach(b=>b.onclick=()=>{selectedThread=b.dataset.thread;renderThreads();renderMessages()});renderMessages()}
 function renderMessages(){const box=document.getElementById('mb3Messages'),form=document.getElementById('mb3MessageForm');if(!box||!form)return;const rows=collab.messages.filter(x=>x.support_request_id===selectedThread);box.innerHTML=selectedThread?(rows.length?rows.map(x=>`<div class="message ${x.sender_type==='customer'?'customer':''}"><div>${esc(x.message)}</div><small>${esc(x.sender_type==='customer'?'You':'Blue Logistics')} • ${new Date(x.created_at).toLocaleString()}</small></div>`).join(''):'<div class="myblue3-empty">No replies yet. Send the first message below.</div>'):'<div class="myblue3-empty">Choose a support request to open its conversation.</div>';form.elements.message.disabled=!selectedThread;form.querySelector('button').disabled=!selectedThread;box.scrollTop=box.scrollHeight}
 function renderClaims(){const box=document.getElementById('mb3Claims');if(!box)return;const rows=collab.claims.filter(x=>x.company_id===cid());box.innerHTML=rows.length?rows.map(x=>`<article class="claim-item"><strong>${esc(x.claim_type)}</strong><small>${esc(x.description.slice(0,120))}</small><span class="status">${esc(x.status)}</span></article>`).join(''):'<div class="myblue3-empty">No claims submitted from this account.</div>'}
 function render(){if(!document.getElementById('myBlue3'))return;fillShipments();renderUpcoming();renderThreads();renderClaims()}
 async function refresh(){try{const d=await api('GET',null,'overview');collab={messages:d.messages||[],claims:d.claims||[]};render()}catch(e){console.warn(e)}}
 async function uploadFile(file,meta={}){if(!file||file.size>10*1024*1024)throw new Error('File must be 10 MB or less.');const c=cid();const pre=await api('POST',{action:'create_upload',company_id:c,name:file.name,mime:file.type,size:file.size});const{error}=await client.storage.from('customer-documents').uploadToSignedUrl(pre.path,pre.token,file,{contentType:file.type||undefined});if(error)throw error;return api('POST',{action:'register_upload',company_id:c,path:pre.path,name:file.name,mime:file.type,size:file.size,...meta})}
 async function uploadDoc(e){e.preventDefault();const f=e.currentTarget,file=f.elements.file.files[0],status=document.getElementById('mb3UploadStatus'),btn=f.querySelector('button');btn.disabled=true;status.textContent='Uploading securely…';try{await uploadFile(file,{shipment_id:f.elements.shipment_id.value||null});status.textContent='✓ Document uploaded to your Blue Logistics account.';f.reset();toast('Document uploaded securely.');setTimeout(()=>typeof loadPortal==='function'&&loadPortal(false),500)}catch(err){status.textContent=err.message;toast(err.message,true)}finally{btn.disabled=false}}
 async function sendMessage(e){e.preventDefault();const f=e.currentTarget,msg=f.elements.message.value.trim();if(!selectedThread||!msg)return;const btn=f.querySelector('button');btn.disabled=true;try{const d=await api('POST',{action:'message',support_request_id:selectedThread,message:msg});collab.messages.push(d.message);f.reset();renderMessages();toast('Message sent.')}catch(err){toast(err.message,true)}finally{btn.disabled=false}}
 async function submitClaim(e){e.preventDefault();const f=e.currentTarget,btn=f.querySelector('button'),file=f.elements.file.files[0];btn.disabled=true;try{const d=await api('POST',{action:'claim',company_id:cid(),shipment_id:f.elements.shipment_id.value,claim_type:f.elements.claim_type.value,amount_claimed:f.elements.amount_claimed.value,description:f.elements.description.value});if(file)await uploadFile(file,{shipment_id:f.elements.shipment_id.value,claim_id:d.claim.id});collab.claims.unshift(d.claim);f.reset();fillShipments();renderClaims();toast('Claim submitted to Blue Logistics.')}catch(err){toast(err.message,true)}finally{btn.disabled=false}}
 function parseCsv(text){const lines=text.split(/\r?\n/).filter(x=>x.trim());if(lines.length<2)return[];const split=l=>{const out=[];let cur='',q=false;for(let i=0;i<l.length;i++){const ch=l[i];if(ch==='"'){if(q&&l[i+1]==='"'){cur+='"';i++}else q=!q}else if(ch===','&&!q){out.push(cur.trim());cur=''}else cur+=ch}out.push(cur.trim());return out};const heads=split(lines[0]).map(x=>x.toLowerCase().replace(/[^a-z0-9]+/g,'_'));return lines.slice(1,51).map(l=>{const a=split(l),o={};heads.forEach((h,i)=>o[h]=a[i]||'');return {origin:o.origin||o.pickup||o.pickup_location||'',destination:o.destination||o.delivery||o.delivery_location||'',equipment_type:o.equipment||o.equipment_type||'',commodity:o.commodity||'',weight:o.weight||'',pickup_date:o.pickup||o.pickup_date||''}}).filter(x=>x.origin&&x.destination)}
 async function loadCsv(){const inp=document.getElementById('mb3Csv'),status=document.getElementById('mb3CsvStatus'),file=inp.files[0];if(!file){status.textContent='Choose a CSV first.';return}const rows=parseCsv(await file.text());if(!rows.length){status.textContent='No valid origin/destination rows found.';return}const tab=document.querySelector('[data-mb2="multilane"]');tab?.click();const tb=document.getElementById('mb2LaneRows');if(!tb){status.textContent='Multi-Lane tool is not ready yet.';return}tb.innerHTML='';rows.forEach(v=>{if(typeof addLaneRow==='function')addLaneRow(v);else{const tr=document.createElement('tr');tr.innerHTML=`<td><input data-k="origin" value="${esc(v.origin)}"></td><td><input data-k="destination" value="${esc(v.destination)}"></td><td><input data-k="equipment_type" value="${esc(v.equipment_type)}"></td><td><input data-k="commodity" value="${esc(v.commodity)}"></td><td><input data-k="weight" value="${esc(v.weight)}"></td><td><input data-k="pickup_date" type="date" value="${esc(v.pickup_date)}"></td>`;tb.appendChild(tr)}});status.textContent=`✓ Loaded ${rows.length} lanes for review.`;document.getElementById('myBlue2Tools')?.scrollIntoView({behavior:'smooth',block:'start'})}
 const baseRender=renderAll;renderAll=function(){baseRender();shell();render();setTimeout(refresh,250)};
 const w=setInterval(()=>{if(!document.getElementById('portalApp')?.hidden){shell();refresh();clearInterval(w)}},500);
})();