(()=>{
 const API='https://scrbdfwpthsylmhtqjeu.supabase.co/functions/v1/customer-portal-intelligence';let intel={attention:[],activity:[],broker_tasks:[]};
 const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
 const cid=()=>currentCompany||portalData?.companies?.[0]?.id||null;
 const session=async()=>{const{data}=await client.auth.getSession();return data.session};
 async function call(method='GET',body=null){const s=await session();if(!s)throw new Error('Sign in required');const url=new URL(API);if(cid())url.searchParams.set('company_id',cid());const o={method,headers:{Authorization:`Bearer ${s.access_token}`,apikey:SUPABASE_KEY,Accept:'application/json'}};if(body){o.headers['Content-Type']='application/json';o.body=JSON.stringify({...body,company_id:cid()})}const r=await fetch(url,o);const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Unable to load intelligence');return d}
 const ships=()=>typeof companyShipments==='function'?companyShipments():[];
 const events=()=>portalData?.events?.filter?.(x=>ships().some(s=>s.id===x.shipment_id))||[];
 const toast=(m,bad=false)=>{let t=document.querySelector('.myblue-toast');if(!t){t=document.createElement('div');t.className='myblue-toast';document.body.appendChild(t)}t.textContent=m;t.classList.toggle('error',bad);clearTimeout(t._i);t._i=setTimeout(()=>t.remove(),4000)};
 function install(){const app=document.getElementById('portalApp');if(!app||document.getElementById('myBlue5'))return;const s=document.createElement('section');s.id='myBlue5';s.className='mb5';s.innerHTML=`<div class="mb5-hero"><span class="portal-kicker">AUTOMATION & INTELLIGENCE</span><h3>What needs your attention?</h3><p>My Blue Logistics watches the account for shipment exceptions, missing PODs, pending appointments and overdue customer-visible invoices, while Blue Logistics receives follow-up tasks for urgent items.</p><div class="mb5-kpis"><div class="mb5-kpi"><span>OPEN ITEMS</span><strong id="mb5Open">0</strong></div><div class="mb5-kpi"><span>URGENT</span><strong id="mb5Urgent">0</strong></div><div class="mb5-kpi"><span>SCHEDULE WATCH</span><strong id="mb5Risk">0</strong></div><div class="mb5-kpi"><span>BLUE FOLLOW-UPS</span><strong id="mb5Tasks">0</strong></div></div></div>
 <div class="mb5-grid"><section class="mb5-card"><span class="portal-kicker">ATTENTION INBOX</span><h3>Items to review</h3><p>These are generated from the live customer account data.</p><div id="mb5Attention" class="mb5-list"></div></section><section class="mb5-card"><span class="portal-kicker">SCHEDULE WATCH</span><h3>Timing risk flags</h3><p>Simple schedule-based flags from published pickup/delivery times—not carrier GPS predictions.</p><div id="mb5RiskList" class="mb5-risk"></div></section></div>
 <div class="mb5-grid"><section class="mb5-card"><span class="portal-kicker">ACCOUNT ACTIVITY</span><h3>Recent customer & shipment activity</h3><div id="mb5Activity" class="mb5-activity"></div></section><section class="mb5-card"><span class="portal-kicker">BLUE LOGISTICS FOLLOW-UP</span><h3>Open broker tasks</h3><p>Urgent portal alerts can automatically create CRM tasks for the Blue Logistics team.</p><div id="mb5TasksList" class="mb5-taskbox"></div></section></div>`;const anchor=document.getElementById('ops4')||document.getElementById('myBlue3')||app.querySelector('.portal-lower-grid');(anchor||app).insertAdjacentElement(anchor?'beforebegin':'beforeend',s);render();refresh()}
 function riskRows(){const now=Date.now(),out=[];for(const s of ships()){if(/deliver|complete|cancel/i.test(s.status||''))continue;let level='',reason='';if(s.exception_note||/exception|delay|hold|issue/i.test(s.status||'')){level='high';reason='Shipment has an active exception or delay flag.'}else if(s.pickup_scheduled_at&&!s.picked_up_at){const h=(new Date(s.pickup_scheduled_at).getTime()-now)/36e5;if(h<0){level='high';reason='Scheduled pickup time has passed and pickup is not posted.'}else if(h<=6){level='med';reason='Pickup is scheduled within 6 hours.'}}else if(s.delivery_scheduled_at&&!s.delivered_at){const h=(new Date(s.delivery_scheduled_at).getTime()-now)/36e5;if(h<0){level='high';reason='Scheduled delivery time has passed and delivery is not posted.'}else if(h<=6){level='med';reason='Delivery is scheduled within 6 hours.'}}if(level)out.push({s,level,reason})}return out}
 function renderKpis(){const a=intel.attention||[],r=riskRows();document.getElementById('mb5Open').textContent=a.length;document.getElementById('mb5Urgent').textContent=a.filter(x=>x.severity==='urgent').length;document.getElementById('mb5Risk').textContent=r.length;document.getElementById('mb5Tasks').textContent=(intel.broker_tasks||[]).length}
 function renderAttention(){const box=document.getElementById('mb5Attention');if(!box)return;const rows=intel.attention||[];if(!rows.length){box.innerHTML='<div class="mb5-empty">Nothing currently needs customer attention.</div>';return}box.innerHTML=rows.map(x=>`<article class="mb5-item ${esc(x.severity)}"><div class="top"><div><strong>${esc(x.title)}</strong><small>${esc(x.details||'')}</small></div><span class="mb5-chip ${esc(x.severity)}">${esc((x.severity||'normal').toUpperCase())}</span></div><div class="mb5-actions"><button class="primary" data-mb5-help="${esc(x.id)}">Ask Blue to Handle</button><button data-mb5-done="${esc(x.id)}">Mark Reviewed</button></div></article>`).join('');box.querySelectorAll('[data-mb5-help]').forEach(b=>b.onclick=()=>createTask(b.dataset.mb5Help));box.querySelectorAll('[data-mb5-done]').forEach(b=>b.onclick=()=>resolve(b.dataset.mb5Done))}
 function renderRisk(){const box=document.getElementById('mb5RiskList');if(!box)return;const rows=riskRows();box.innerHTML=rows.length?rows.map(({s,level,reason})=>`<article class="mb5-risk-row"><div class="route"><strong>${esc(s.reference_number)} · ${esc(s.origin)} → ${esc(s.destination)}</strong><small>${esc(reason)}</small></div><span class="mb5-risk-tag ${level}">${level==='high'?'HIGH':'WATCH'}</span></article>`).join(''):'<div class="mb5-empty">No schedule-based risk flags right now.</div>'}
 function unifiedActivity(){const stored=(intel.activity||[]).map(x=>({title:x.title,details:x.details,at:x.created_at,type:x.actor_type||'portal'}));const shipment=events().map(x=>({title:x.title||x.status||'Shipment updated',details:x.details||x.location||'',at:x.occurred_at,type:'shipment'}));return [...stored,...shipment].filter(x=>x.at).sort((a,b)=>new Date(b.at)-new Date(a.at)).slice(0,40)}
 function renderActivity(){const box=document.getElementById('mb5Activity');if(!box)return;const rows=unifiedActivity();box.innerHTML=rows.length?rows.map(x=>`<div class="mb5-activity-row"><strong>${esc(x.title)}</strong><small>${esc(x.details||'')} ${x.at?'• '+new Date(x.at).toLocaleString():''}</small></div>`).join(''):'<div class="mb5-empty">Activity will appear here as the account is used and shipments are updated.</div>'}
 function renderTasks(){const box=document.getElementById('mb5TasksList');if(!box)return;const rows=(intel.broker_tasks||[]).slice(0,12);box.innerHTML=rows.length?rows.map(x=>`<article class="mb5-task"><strong>${esc(x.title)}</strong><small>${esc(x.priority||'Normal')}${x.due_at?' • Due '+new Date(x.due_at).toLocaleString():''}</small></article>`).join(''):'<div class="mb5-empty">No open Blue Logistics follow-up tasks are linked to this account.</div>'}
 function render(){if(!document.getElementById('myBlue5'))return;renderKpis();renderAttention();renderRisk();renderActivity();renderTasks()}
 async function refresh(){try{intel=await call('GET');render()}catch(err){console.warn(err)}}
 async function createTask(id){const a=intel.attention.find(x=>x.id===id);if(!a)return;try{const d=await call('POST',{action:'create_broker_task',title:`Customer requested help: ${a.title}`,description:`${a.details||''}\nAttention item: ${a.id}`,priority:a.severity==='urgent'?'Urgent':'Normal',due_hours:a.severity==='urgent'?1:4});intel.broker_tasks.unshift(d.task);toast('Blue Logistics follow-up created.');render()}catch(err){toast(err.message,true)}}
 async function resolve(id){try{await call('POST',{action:'resolve_attention',id});intel.attention=intel.attention.filter(x=>x.id!==id);toast('Marked reviewed.');render()}catch(err){toast(err.message,true)}}
 const baseRender=renderAll;renderAll=function(){baseRender();install();render();setTimeout(refresh,220)};
 const w=setInterval(()=>{if(!document.getElementById('portalApp')?.hidden){install();refresh();clearInterval(w)}},500);
})();