(()=>{
 const ACTIONS_API='https://scrbdfwpthsylmhtqjeu.supabase.co/functions/v1/customer-portal-actions';
 let savedLanes=[];
 const toast=(msg,error=false)=>{let t=document.querySelector('.myblue-toast');if(!t){t=document.createElement('div');t.className='myblue-toast';document.body.appendChild(t)}t.textContent=msg;t.classList.toggle('error',error);clearTimeout(t._timer);t._timer=setTimeout(()=>t.remove(),4200)};
 const getSession=async()=>{const{data}=await client.auth.getSession();return data.session||null};
 async function actionApi(method='GET',body=null){const session=await getSession();if(!session)throw new Error('Sign in required');const opts={method,headers:{Authorization:`Bearer ${session.access_token}`,apikey:SUPABASE_KEY,Accept:'application/json'}};if(body){opts.headers['Content-Type']='application/json';opts.body=JSON.stringify(body)}const r=await fetch(ACTIONS_API,opts);const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||'Portal action failed');return data}
 const esc2=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
 function currentCompanyId(){return currentCompany||portalData?.companies?.[0]?.id||null}
 function installShell(){const app=document.getElementById('portalApp');if(!app||document.querySelector('.myblue-actions'))return;const command=app.querySelector('.portal-command');const actions=document.createElement('div');actions.className='myblue-actions';actions.innerHTML='<a class="myblue-action primary" href="contact.html#quote"><span>＋</span><div><strong>New Freight Quote</strong><small>Start a shipment request</small></div></a><button type="button" class="myblue-action" id="myBlueRequote"><span>↻</span><div><strong>Re-Quote a Lane</strong><small>Use a saved or recent lane</small></div></button><a class="myblue-action" href="#shipmentList"><span>⌖</span><div><strong>Track Shipment</strong><small>Open active freight</small></div></a><a class="myblue-action" href="#documentList"><span>▤</span><div><strong>Documents</strong><small>BOL, POD and files</small></div></a>';command.insertAdjacentElement('afterend',actions);
 const grid=document.createElement('div');grid.className='myblue-grid';grid.innerHTML='<section class="myblue-panel"><div class="myblue-panel-head"><div><span class="portal-kicker">SAVED LANES</span><h3>Ship regular routes faster</h3><p>Save repeat pickup and delivery lanes for one-click re-quoting.</p></div></div><div id="savedLaneList" class="saved-lane-list"></div><details><summary style="cursor:pointer;font-weight:800;margin-top:12px">＋ Save a lane</summary><form id="saveLaneForm" class="save-lane-form"><label>Label<input name="label" placeholder="e.g. Raleigh to Atlanta"></label><label>Equipment<select name="equipment_type"><option value="">Not sure</option><option>Dry Van</option><option>Reefer</option><option>Flatbed</option><option>LTL Common Carrier</option><option>Drayage / Container</option><option>Other</option></select></label><label class="full">Origin<input required name="origin" placeholder="City, State or ZIP"></label><label class="full">Destination<input required name="destination" placeholder="City, State or ZIP"></label><label class="full">Commodity<input name="commodity" placeholder="Optional"></label><button class="btn primary" type="submit">Save Lane →</button></form></details></section><section class="myblue-panel"><div class="myblue-panel-head"><div><span class="portal-kicker">QUOTE STATUS</span><h3>Know where pricing stands</h3><p>Received → Pricing → Quote Ready → Accepted.</p></div></div><div id="quoteStatusList" class="quote-status-list"></div></section>';actions.insertAdjacentElement('afterend',grid);
 document.getElementById('saveLaneForm')?.addEventListener('submit',saveLane);
 document.getElementById('myBlueRequote')?.addEventListener('click',()=>{const lane=savedLanes[0]||deriveRecentLane();if(!lane)return toast('No saved or recent lane is available yet.',true);requote(lane)});
 }
 function deriveRecentLane(){const s=companyShipments?.()?.[0];if(s)return {origin:s.origin,destination:s.destination,equipment_type:s.equipment_type,commodity:s.commodity};const q=companyQuotes?.()?.[0];return q?{origin:q.origin,destination:q.destination,equipment_type:q.equipment_type}:null}
 function renderSaved(){const box=document.getElementById('savedLaneList');if(!box)return;const rows=savedLanes.filter(x=>x.company_id===currentCompanyId());if(!rows.length){box.innerHTML='<div class="portal-empty-inline">No saved lanes yet. Save a regular route or use a recent shipment to create one.</div>';return}box.innerHTML=rows.map(l=>`<article class="saved-lane"><div class="saved-lane-top"><div><div class="saved-lane-route">${esc2(l.origin)} → ${esc2(l.destination)}</div><div class="saved-lane-meta">${esc2(l.label||'Saved lane')}${l.equipment_type?` • ${esc2(l.equipment_type)}`:''}${l.commodity?` • ${esc2(l.commodity)}`:''}</div></div></div><div class="saved-lane-actions"><button class="requote" data-requote="${esc2(l.id)}">Request New Quote</button><button class="remove" data-remove-lane="${esc2(l.id)}">Remove</button></div></article>`).join('');box.querySelectorAll('[data-requote]').forEach(b=>b.addEventListener('click',()=>{const lane=savedLanes.find(x=>x.id===b.dataset.requote);if(lane)requote(lane)}));box.querySelectorAll('[data-remove-lane]').forEach(b=>b.addEventListener('click',()=>removeLane(b.dataset.removeLane,b)))}
 async function loadSaved(){try{const data=await actionApi('GET');savedLanes=data.saved_lanes||[];renderSaved()}catch(err){console.warn(err)}}
 async function saveLane(e){e.preventDefault();const f=e.currentTarget,fd=new FormData(f),btn=f.querySelector('button');btn.disabled=true;try{const data=await actionApi('POST',{action:'save_lane',company_id:currentCompanyId(),label:fd.get('label'),origin:fd.get('origin'),destination:fd.get('destination'),equipment_type:fd.get('equipment_type'),commodity:fd.get('commodity')});savedLanes.unshift(data.lane);f.reset();renderSaved();toast('Saved lane added.')}catch(err){toast(err.message,true)}finally{btn.disabled=false}}
 async function removeLane(id,btn){btn.disabled=true;try{await actionApi('POST',{action:'delete_lane',id});savedLanes=savedLanes.filter(x=>x.id!==id);renderSaved();toast('Saved lane removed.')}catch(err){toast(err.message,true);btn.disabled=false}}
 function requote(lane){try{sessionStorage.setItem('blue_portal_requote',JSON.stringify({pickup_location:lane.origin||'',delivery_location:lane.destination||'',equipment_type:lane.equipment_type||'',commodity:lane.commodity||''}))}catch{}location.href='index.html#quoteForm'}
 function quoteStage(q){const s=String(q.status||'').toLowerCase();if(s.includes('accept'))return 4;if(q.customer_rate!==null&&q.customer_rate!==undefined||s.includes('sent')||s.includes('ready'))return 3;if(s.includes('pricing')||s.includes('working')||s.includes('review'))return 2;return 1}
 function renderQuoteStatus(){const box=document.getElementById('quoteStatusList');if(!box||!portalData)return;const qs=companyQuotes().slice(0,6);if(!qs.length){box.innerHTML='<div class="portal-empty-inline">Your quote requests will appear here when they are linked to this customer account.</div>';return}box.innerHTML=qs.map(q=>{const st=quoteStage(q);return `<article class="saved-lane"><div class="saved-lane-top"><div><div class="saved-lane-route">${esc2(q.origin||'Origin')} → ${esc2(q.destination||'Destination')}</div><div class="saved-lane-meta">${esc2(q.quote_number||'Quote')} • ${esc2(q.status||'Received')}</div></div>${q.customer_rate!==null&&q.customer_rate!==undefined?`<strong>${esc2(money(q.customer_rate))}</strong>`:''}</div><div class="quote-progress"><i class="${st>=1?'done':''}"></i><i class="${st>=2?'done':''}"></i><i class="${st>=3?'done':''}"></i><i class="${st>=4?'done':''}"></i></div><div class="quote-progress-label">${st===1?'Received':st===2?'Pricing in progress':st===3?'Quote ready': 'Accepted'}</div></article>`}).join('')}
 function enhanceQuoteRows(){const list=document.getElementById('quoteList');if(!list||!portalData)return;const quotes=companyQuotes().slice(0,15);const rows=[...list.querySelectorAll('.quote-row')];rows.forEach((row,i)=>{const q=quotes[i];if(!q||row.dataset.myblue)return;row.dataset.myblue='1';row.classList.add('myblue-quote');const right=row.lastElementChild;if(!right)return;right.classList.add('quote-row-actions');const st=quoteStage(q);if(st===4){const note=document.createElement('small');note.className='accept-note';note.textContent='✓ Accepted by customer';right.appendChild(note)}else if(st===3&&q.customer_rate!==null&&q.customer_rate!==undefined){const b=document.createElement('button');b.type='button';b.textContent='Accept Quote';b.addEventListener('click',()=>acceptQuote(q,b));right.appendChild(b)}const rq=document.createElement('button');rq.type='button';rq.style.background='#eff3f7';rq.style.color='#53687d';rq.textContent='Re-Quote Lane';rq.addEventListener('click',()=>requote({origin:q.origin,destination:q.destination,equipment_type:q.equipment_type}));right.appendChild(rq)})}
 async function acceptQuote(q,btn){if(!confirm(`Accept ${q.quote_number||'this quote'} for ${money(q.customer_rate)}? This tells Blue Logistics you approve the quoted price.`))return;btn.disabled=true;btn.textContent='Accepting…';try{await actionApi('POST',{action:'accept_quote',quote_id:q.id,company_id:q.company_id});q.status='Accepted';toast('Quote accepted. Blue Logistics has been notified in the portal audit trail.');renderQuotes();setTimeout(()=>{enhanceQuoteRows();renderQuoteStatus()},30)}catch(err){toast(err.message,true);btn.disabled=false;btn.textContent='Accept Quote'}}
 const originalRenderAll=renderAll;renderAll=function(){originalRenderAll();installShell();renderSaved();renderQuoteStatus();setTimeout(enhanceQuoteRows,0)};
 const originalRenderQuotes=renderQuotes;renderQuotes=function(){originalRenderQuotes();setTimeout(()=>{enhanceQuoteRows();renderQuoteStatus()},0)};
 client.auth.onAuthStateChange((event,session)=>{if(event==='SIGNED_IN'&&session)setTimeout(loadSaved,500)});
 const watch=setInterval(()=>{if(!document.getElementById('portalApp')?.hidden){installShell();loadSaved();renderQuoteStatus();enhanceQuoteRows();clearInterval(watch)}},500);
})();