(()=>{
 const API='https://scrbdfwpthsylmhtqjeu.supabase.co/functions/v1/customer-portal-ops';let ops={appointments:[],invoices:[]},activeTab='overview';
 const e=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
 const cid=()=>currentCompany||portalData?.companies?.[0]?.id||null;
 const session=async()=>{const{data}=await client.auth.getSession();return data.session};
 async function api(method='GET',body=null){const s=await session();if(!s)throw new Error('Sign in required');const o={method,headers:{Authorization:`Bearer ${s.access_token}`,apikey:SUPABASE_KEY,Accept:'application/json'}};if(body){o.headers['Content-Type']='application/json';o.body=JSON.stringify(body)}const r=await fetch(API,o);const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Unable to complete operation');return d}
 const ships=()=>typeof companyShipments==='function'?companyShipments():[];
 const docs=()=>typeof companyDocs==='function'?companyDocs():[];
 const m=v=>v===null||v===undefined?'—':new Intl.NumberFormat(undefined,{style:'currency',currency:'USD',maximumFractionDigits:0}).format(Number(v||0));
 const dt=v=>v?new Intl.DateTimeFormat(undefined,{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}).format(new Date(v)):'—';
 const toast=(x,bad=false)=>{let t=document.querySelector('.myblue-toast');if(!t){t=document.createElement('div');t.className='myblue-toast';document.body.appendChild(t)}t.textContent=x;t.classList.toggle('error',bad);clearTimeout(t._o);t._o=setTimeout(()=>t.remove(),4000)};
 function install(){const app=document.getElementById('portalApp');if(!app||document.getElementById('ops4'))return;const s=document.createElement('section');s.id='ops4';s.className='ops4';s.innerHTML=`<div class="ops4-hero"><span class="portal-kicker">OPERATIONS CONTROL CENTER</span><h3>Your freight at a glance</h3><p>Search shipments, watch exceptions, plan appointments, open PODs and review customer invoice status from one place.</p><div class="ops4-kpis"><div class="ops4-kpi"><span>ACTIVE</span><strong id="ops4Active">0</strong></div><div class="ops4-kpi"><span>EXCEPTIONS</span><strong id="ops4Exceptions">0</strong></div><div class="ops4-kpi"><span>NEXT 7 DAYS</span><strong id="ops4Week">0</strong></div><div class="ops4-kpi"><span>POD READY</span><strong id="ops4Pod">0</strong></div><div class="ops4-kpi"><span>OPEN INVOICES</span><strong id="ops4OpenInvoices">0</strong></div></div></div>
 <div class="ops4-toolbar"><div><div class="ops4-search"><input id="ops4Search" placeholder="Search shipment #, customer ref, origin, destination, commodity..."></div><div id="ops4SearchResults" class="ops4-search-results"></div></div><div class="ops4-tabs"><button class="active" data-ops4="overview">Overview</button><button data-ops4="calendar">Calendar</button><button data-ops4="exceptions">Exceptions</button><button data-ops4="appointments">Appointments</button><button data-ops4="billing">Billing</button></div></div>
 <div class="ops4-panel active" data-ops4-panel="overview"><div class="ops4-grid"><section class="ops4-card"><span class="portal-kicker">EXECUTIVE SUMMARY</span><h3>Account snapshot</h3><div id="ops4Summary" class="ops4-list"></div></section><section class="ops4-card"><span class="portal-kicker">POD READY</span><h3>Delivery documents</h3><div id="ops4PodList" class="ops4-list"></div></section></div></div>
 <div class="ops4-panel" data-ops4-panel="calendar"><section class="ops4-card"><span class="portal-kicker">FREIGHT CALENDAR</span><h3>Pickup & delivery schedule</h3><p>Next 28 days of scheduled activity.</p><div id="ops4Calendar" class="ops4-calendar"></div></section></div>
 <div class="ops4-panel" data-ops4-panel="exceptions"><section class="ops4-card"><span class="portal-kicker">EXCEPTIONS</span><h3>Loads that need attention</h3><div id="ops4ExceptionList" class="ops4-list"></div></section></div>
 <div class="ops4-panel" data-ops4-panel="appointments"><div class="ops4-grid"><section class="ops4-card"><span class="portal-kicker">APPOINTMENT REQUESTS</span><h3>Pickup & delivery requests</h3><div id="ops4AppointmentList" class="ops4-list"></div></section><section class="ops4-card"><h3>Request an appointment</h3><p>Blue Logistics will review and coordinate this request. Submitting it does not confirm the appointment.</p><form id="ops4AppointmentForm" class="ops4-form"><label class="full">Shipment<select required name="shipment_id" id="ops4ShipmentSelect"></select></label><label>Type<select name="appointment_type"><option>Pickup</option><option>Delivery</option></select></label><label>Date<input required type="date" name="requested_date"></label><label class="full">Preferred window<input name="requested_window" placeholder="e.g. 8 AM–12 PM"></label><label>Facility contact<input name="contact_name"></label><label>Phone<input name="contact_phone" type="tel"></label><label class="full">Facility notes<textarea name="facility_notes" rows="3" placeholder="Receiving hours, appointment #, dock instructions..."></textarea></label><button class="btn primary full" type="submit">Request Appointment →</button></form></section></div></div>
 <div class="ops4-panel" data-ops4-panel="billing"><section class="ops4-card"><span class="portal-kicker">INVOICES & PAYMENT STATUS</span><h3>Customer-visible billing records</h3><p>Invoice status appears here when Blue Logistics publishes it to your account. Payment links only appear when one has been configured.</p><div id="ops4InvoiceList" class="ops4-list"></div></section></div>`;const anchor=document.getElementById('myBlue3')||app.querySelector('.portal-lower-grid');(anchor||app).insertAdjacentElement(anchor?'beforebegin':'beforeend',s);
 document.querySelectorAll('[data-ops4]').forEach(b=>b.addEventListener('click',()=>switchTab(b.dataset.ops4)));
 document.getElementById('ops4Search').addEventListener('input',renderSearch);
 document.getElementById('ops4AppointmentForm').addEventListener('submit',requestAppointment);
 render();refresh();}
 function switchTab(tab){activeTab=tab;document.querySelectorAll('[data-ops4]').forEach(x=>x.classList.toggle('active',x.dataset.ops4===tab));document.querySelectorAll('[data-ops4-panel]').forEach(x=>x.classList.toggle('active',x.dataset.ops4Panel===tab));}
 function accountInvoices(){return ops.invoices.filter(x=>x.company_id===cid())}
 function accountAppointments(){return ops.appointments.filter(x=>x.company_id===cid())}
 function podDocs(){return docs().filter(d=>/\bpod\b|proof.?of.?delivery/i.test(`${d.document_type||''} ${d.original_name||''}`))}
 function exceptionShips(){return ships().filter(x=>x.exception_note||/exception|delay|hold|issue/i.test(x.status||''))}
 function renderKpis(){const now=Date.now(),week=now+7*864e5;document.getElementById('ops4Active').textContent=ships().filter(x=>!/deliver|complete|cancel/i.test(x.status||'')).length;document.getElementById('ops4Exceptions').textContent=exceptionShips().length;document.getElementById('ops4Week').textContent=ships().filter(x=>{const t=new Date(x.pickup_scheduled_at||x.delivery_scheduled_at||0).getTime();return t>=now&&t<=week}).length;document.getElementById('ops4Pod').textContent=podDocs().length;document.getElementById('ops4OpenInvoices').textContent=accountInvoices().filter(x=>!/paid|closed|void/i.test(x.status||'')).length}
 function renderSummary(){const box=document.getElementById('ops4Summary');if(!box)return;const ss=ships(),active=ss.filter(x=>!/deliver|complete|cancel/i.test(x.status||'')),delivered30=ss.filter(x=>x.delivered_at&&Date.now()-new Date(x.delivered_at).getTime()<=30*864e5),rate=ss.reduce((a,x)=>a+Number(x.customer_rate||0),0);box.innerHTML=`<article class="ops4-row"><div class="right"><strong>${active.length} active shipment${active.length===1?'':'s'}</strong><span class="ops4-badge">LIVE</span></div><small>${exceptionShips().length?`${exceptionShips().length} currently flagged for attention`:'No active exception notes'}</small></article><article class="ops4-row"><strong>${delivered30.length} delivered in the last 30 days</strong><small>${podDocs().length} POD document${podDocs().length===1?'':'s'} currently visible</small></article><article class="ops4-row"><strong>${m(rate)} visible shipment value</strong><small>Total of customer rates currently present in this portal account; not an accounting statement.</small></article>`}
 function renderPods(){const box=document.getElementById('ops4PodList');if(!box)return;const rows=podDocs().slice(0,10);if(!rows.length){box.innerHTML='<div class="ops4-empty">No POD documents are currently visible.</div>';return}box.innerHTML=rows.map(d=>{const s=ships().find(x=>x.id===d.shipment_id);return `<article class="ops4-row"><div class="right"><div><strong>${e(s?.reference_number||d.original_name)}</strong><small>${e(s?`${s.origin} → ${s.destination}`:d.original_name)}</small></div><button class="portal-ghost" data-ops4-doc="${e(d.id)}">Open POD</button></div></article>`}).join('');box.querySelectorAll('[data-ops4-doc]').forEach(b=>b.onclick=async()=>{try{const data=await window.api('document',{id:b.dataset.ops4Doc});window.open(data.url,'_blank','noopener,noreferrer')}catch(err){toast(err.message,true)}})}
 function renderCalendar(){const box=document.getElementById('ops4Calendar');if(!box)return;const start=new Date();start.setHours(0,0,0,0);const days=[];for(let i=0;i<28;i++){const d=new Date(start);d.setDate(start.getDate()+i);const key=d.toISOString().slice(0,10);const events=[];ships().forEach(s=>{if(s.pickup_scheduled_at&&new Date(s.pickup_scheduled_at).toISOString().slice(0,10)===key)events.push({kind:'pickup',text:`PICKUP · ${s.reference_number} · ${s.origin}`});if(s.delivery_scheduled_at&&new Date(s.delivery_scheduled_at).toISOString().slice(0,10)===key)events.push({kind:'delivery',text:`DELIVERY · ${s.reference_number} · ${s.destination}`})});days.push(`<div class="ops4-day"><div class="date">${d.toLocaleDateString(undefined,{weekday:'short',month:'short',day:'numeric'})}</div>${events.map(x=>`<div class="ops4-event ${x.kind==='delivery'?'delivery':''}">${e(x.text)}</div>`).join('')}</div>`)}box.innerHTML=days.join('')}
 function renderExceptions(){const box=document.getElementById('ops4ExceptionList');if(!box)return;const rows=exceptionShips();box.innerHTML=rows.length?rows.map(s=>`<article class="ops4-row"><div class="right"><strong>${e(s.reference_number)} · ${e(s.origin)} → ${e(s.destination)}</strong><span class="ops4-badge bad">ATTENTION</span></div><small>${e(s.exception_note||s.status||'Shipment issue')}</small></article>`).join(''):'<div class="ops4-empty">No shipment exceptions are currently flagged.</div>'}
 function renderAppointments(){const box=document.getElementById('ops4AppointmentList'),sel=document.getElementById('ops4ShipmentSelect');if(sel)sel.innerHTML='<option value="">Choose shipment</option>'+ships().filter(x=>!/deliver|complete|cancel/i.test(x.status||'')).map(x=>`<option value="${e(x.id)}">${e(x.reference_number)} · ${e(x.origin)} → ${e(x.destination)}</option>`).join('');if(!box)return;const rows=accountAppointments();box.innerHTML=rows.length?rows.map(a=>{const s=ships().find(x=>x.id===a.shipment_id);return `<article class="ops4-row"><div class="right"><strong>${e(a.appointment_type)} · ${e(s?.reference_number||'Shipment')}</strong><span class="ops4-badge ${/confirm|approved/i.test(a.status)?'good':/declin|cancel/i.test(a.status)?'bad':'warn'}">${e(a.status)}</span></div><small>${e(a.requested_date)}${a.requested_window?` · ${e(a.requested_window)}`:''}</small></article>`}).join(''):'<div class="ops4-empty">No appointment requests have been submitted from this account.</div>'}
 function renderInvoices(){const box=document.getElementById('ops4InvoiceList');if(!box)return;const rows=accountInvoices();box.innerHTML=rows.length?rows.map(i=>`<article class="ops4-row ops4-invoice"><div><div class="right"><strong>${e(i.invoice_number)} · ${e(m(i.amount))}</strong><span class="ops4-badge ${/paid/i.test(i.status)?'good':/past|overdue/i.test(i.status)?'bad':'warn'}">${e(i.status)}</span></div><small>${i.due_date?`Due ${e(i.due_date)}`:'No due date published'}${i.paid_at?` · Paid ${e(new Date(i.paid_at).toLocaleDateString())}`:''}</small></div>${i.external_payment_url&&!/paid/i.test(i.status)?`<a class="ops4-pay" target="_blank" rel="noopener" href="${e(i.external_payment_url)}">Open Payment Link</a>`:''}</article>`).join(''):'<div class="ops4-empty">No customer-visible invoices have been published to this portal account yet.</div>'}
 function renderSearch(){const q=document.getElementById('ops4Search').value.trim().toLowerCase(),box=document.getElementById('ops4SearchResults');if(!q){box.innerHTML='';return}const rows=ships().filter(s=>[s.reference_number,s.customer_reference,s.origin,s.destination,s.commodity,s.equipment_type,s.status].some(v=>String(v||'').toLowerCase().includes(q))).slice(0,12);box.innerHTML=rows.length?rows.map(s=>`<button class="ops4-search-hit" data-hit="${e(s.id)}"><strong>${e(s.reference_number)} · ${e(s.origin)} → ${e(s.destination)}</strong><small>${e(s.status)}${s.customer_reference?` · Ref ${e(s.customer_reference)}`:''}</small></button>`).join(''):'<div class="ops4-empty">No matching shipments.</div>';box.querySelectorAll('[data-hit]').forEach(b=>b.onclick=()=>{currentShipment=b.dataset.hit;shipmentFilter='all';document.querySelectorAll('.portal-filter button').forEach(x=>x.classList.toggle('active',x.dataset.filter==='all'));renderShipments();renderDetail();document.getElementById('shipmentList')?.scrollIntoView({behavior:'smooth',block:'start'})})}
 async function requestAppointment(ev){ev.preventDefault();const f=ev.currentTarget,btn=f.querySelector('button'),fd=Object.fromEntries(new FormData(f));btn.disabled=true;btn.textContent='Sending…';try{const d=await api('POST',{action:'request_appointment',company_id:cid(),...fd});ops.appointments.unshift(d.appointment);f.reset();renderAppointments();renderKpis();toast('Appointment request sent to Blue Logistics.')}catch(err){toast(err.message,true)}finally{btn.disabled=false;btn.textContent='Request Appointment →'}}
 async function refresh(){try{const d=await api();ops={appointments:d.appointments||[],invoices:d.invoices||[]};render()}catch(err){console.warn(err)}}
 function render(){if(!document.getElementById('ops4'))return;renderKpis();renderSummary();renderPods();renderCalendar();renderExceptions();renderAppointments();renderInvoices();renderSearch()}
 const baseRender=renderAll;renderAll=function(){baseRender();install();render();setTimeout(refresh,200)};
 const w=setInterval(()=>{if(!document.getElementById('portalApp')?.hidden){install();refresh();clearInterval(w)}},500);
})();