const SUPABASE_URL='https://scrbdfwpthsylmhtqjeu.supabase.co';
const SUPABASE_KEY='sb_publishable_AezQqW-5YRH2wF69ePpalw_sdmMJvgQ';
const PORTAL_API=`${SUPABASE_URL}/functions/v1/customer-portal-api`;
const client=supabase.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,detectSessionInUrl:true,autoRefreshToken:true}});
const $=id=>document.getElementById(id);
const login=$('portalLogin'),app=$('portalApp'),notice=$('portalNotice'),loginForm=$('portalLoginForm'),loginButton=$('portalLoginButton'),loginStatus=$('portalLoginStatus');
let portalData=null,currentCompany=null,currentShipment=null,shipmentFilter='active';
$('year').textContent=new Date().getFullYear();

const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const fmtDate=v=>v?new Intl.DateTimeFormat(undefined,{month:'short',day:'numeric',year:'numeric'}).format(new Date(v)):'—';
const fmtDateTime=v=>v?new Intl.DateTimeFormat(undefined,{month:'short',day:'numeric',year:'numeric',hour:'numeric',minute:'2-digit'}).format(new Date(v)):'—';
const money=v=>v===null||v===undefined||v===''?'—':new Intl.NumberFormat(undefined,{style:'currency',currency:'USD',maximumFractionDigits:0}).format(Number(v||0));
const size=v=>{const n=Number(v||0);if(!n)return'';if(n<1024)return`${n} B`;if(n<1048576)return`${Math.round(n/1024)} KB`;return`${(n/1048576).toFixed(1)} MB`};
const delivered=s=>/delivered|complete/i.test(String(s||''));
const cancelled=s=>/cancel/i.test(String(s||''));
const activeShipment=s=>!delivered(s.status)&&!cancelled(s.status);
function showNotice(text,type='info'){notice.textContent=text;notice.className=`portal-notice ${type}`;notice.hidden=false}
function hideNotice(){notice.hidden=true}
function statusClass(status=''){const x=String(status).toLowerCase();if(x.includes('deliver'))return'delivered';if(x.includes('exception'))return'exception';if(x.includes('transit')||x.includes('dispatch')||x.includes('loaded'))return'transit';if(x.includes('book')||x.includes('assign')||x.includes('pickup'))return'booked';if(x.includes('cancel'))return'cancelled';return'neutral'}

async function getSession(){const{data}=await client.auth.getSession();return data.session||null}
async function api(action='portal',params={}){const session=await getSession();if(!session)throw new Error('Sign in required');const url=new URL(PORTAL_API);url.searchParams.set('action',action);Object.entries(params).forEach(([k,v])=>url.searchParams.set(k,v));const r=await fetch(url,{headers:{Authorization:`Bearer ${session.access_token}`,apikey:SUPABASE_KEY,Accept:'application/json'},cache:'no-store'});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||'Portal request failed');return data}

loginForm.addEventListener('submit',async e=>{e.preventDefault();hideNotice();const email=$('portalEmail').value.trim().toLowerCase();if(!email)return;loginButton.disabled=true;loginButton.textContent='Sending secure link…';loginStatus.textContent='Check your inbox for the Blue Logistics sign-in link.';try{const redirect=`${location.origin}/portal.html`;const{error}=await client.auth.signInWithOtp({email,options:{emailRedirectTo:redirect,shouldCreateUser:true}});if(error)throw error;loginStatus.textContent='✓ Secure sign-in link sent. Open it from this device to enter your portal.';loginStatus.className='success'}catch(err){loginStatus.textContent=err.message||'Unable to send sign-in link.';loginStatus.className='error'}finally{loginButton.disabled=false;loginButton.textContent='Email My Secure Sign-In Link →'}});

$('portalLogout').addEventListener('click',async()=>{await client.auth.signOut();portalData=null;currentShipment=null;app.hidden=true;login.hidden=false;showNotice('You have been signed out securely.','info')});
$('portalRefresh').addEventListener('click',()=>loadPortal(true));
$('portalCompanySelect').addEventListener('change',e=>{currentCompany=e.target.value;currentShipment=null;renderAll()});
document.querySelectorAll('.portal-filter button').forEach(b=>b.addEventListener('click',()=>{shipmentFilter=b.dataset.filter;document.querySelectorAll('.portal-filter button').forEach(x=>x.classList.toggle('active',x===b));renderShipments()}));
$('documentFilter').addEventListener('change',renderDocuments);

async function loadPortal(manual=false){hideNotice();if(manual){$('portalRefresh').disabled=true;$('portalRefresh').textContent='Refreshing…'}try{portalData=await api('portal');login.hidden=true;app.hidden=false;const ids=(portalData.companies||[]).map(c=>c.id);if(!currentCompany||!ids.includes(currentCompany))currentCompany=ids[0]||null;renderAll()}catch(err){app.hidden=true;login.hidden=false;showNotice(err.message||'Unable to load your account.','error')}finally{if(manual){$('portalRefresh').disabled=false;$('portalRefresh').textContent='↻ Refresh'}}}

function company(){return(portalData?.companies||[]).find(c=>c.id===currentCompany)||null}
function companyShipments(){return(portalData?.shipments||[]).filter(s=>s.company_id===currentCompany)}
function companyDocs(){return(portalData?.documents||[]).filter(d=>d.company_id===currentCompany)}
function companyQuotes(){return(portalData?.quotes||[]).filter(q=>q.company_id===currentCompany)}
function shipmentEvents(id){return(portalData?.events||[]).filter(e=>e.shipment_id===id).sort((a,b)=>new Date(b.occurred_at)-new Date(a.occurred_at))}

function renderAll(){const c=company();$('portalCompanyName').textContent=c?.actual_company_name||c?.company_name||'Your Account';$('portalUserLine').textContent=`Signed in as ${portalData?.user?.email||''}${c?.assigned_to?` • Blue Logistics contact: ${c.assigned_to}`:''}`;const select=$('portalCompanySelect');select.innerHTML=(portalData.companies||[]).map(x=>`<option value="${esc(x.id)}" ${x.id===currentCompany?'selected':''}>${esc(x.actual_company_name||x.company_name)}</option>`).join('');select.hidden=(portalData.companies||[]).length<=1;const ships=companyShipments(),docs=companyDocs(),quotes=companyQuotes();$('metricActive').textContent=ships.filter(activeShipment).length;$('metricDelivered').textContent=ships.filter(s=>delivered(s.status)).length;$('metricDocs').textContent=docs.length;$('metricQuotes').textContent=quotes.length;renderShipments();buildDocumentFilter();renderDocuments();renderQuotes();renderDetail()}

function renderShipments(){const ships=companyShipments().filter(s=>shipmentFilter==='all'||shipmentFilter==='delivered'?shipmentFilter==='all'||delivered(s.status):activeShipment(s));const list=$('shipmentList');if(!ships.length){list.innerHTML=`<div class="portal-empty small"><span>📦</span><h3>No ${shipmentFilter==='all'?'':shipmentFilter} shipments</h3><p>Shipment records will appear here as your Blue Logistics team adds them.</p></div>`;if(currentShipment&&!companyShipments().some(s=>s.id===currentShipment))currentShipment=null;renderDetail();return}if(!currentShipment||!ships.some(s=>s.id===currentShipment))currentShipment=ships[0].id;list.innerHTML=ships.map(s=>`<button class="shipment-card ${s.id===currentShipment?'selected':''}" data-id="${esc(s.id)}"><div class="shipment-card-top"><strong>${esc(s.reference_number)}</strong><span class="status-pill ${statusClass(s.status)}">${esc(s.status)}</span></div><div class="shipment-route"><b>${esc(s.origin)}</b><span>→</span><b>${esc(s.destination)}</b></div><div class="shipment-meta"><span>${esc(s.equipment_type||'Equipment pending')}</span><span>${s.pickup_scheduled_at?`Pickup ${esc(fmtDate(s.pickup_scheduled_at))}`:'Pickup TBD'}</span></div>${s.exception_note?`<div class="shipment-alert">⚠ ${esc(s.exception_note)}</div>`:''}</button>`).join('');list.querySelectorAll('.shipment-card').forEach(btn=>btn.addEventListener('click',()=>{currentShipment=btn.dataset.id;renderShipments();renderDetail();$('documentFilter').value=currentShipment;renderDocuments()}));renderDetail()}

function renderDetail(){const box=$('shipmentDetail'),s=companyShipments().find(x=>x.id===currentShipment);if(!s){box.innerHTML=`<div class="portal-empty"><span>🚛</span><h3>Select a shipment</h3><p>Choose a shipment from the tracking board to open its complete timeline and documents.</p></div>`;return}const events=shipmentEvents(s.id);const latest=events[0];const docs=companyDocs().filter(d=>d.shipment_id===s.id);box.innerHTML=`<div class="shipment-detail-head"><div><span class="portal-kicker">SHIPMENT ${esc(s.reference_number)}</span><h3>${esc(s.origin)} → ${esc(s.destination)}</h3></div><span class="status-pill ${statusClass(s.status)}">${esc(s.status)}</span></div><div class="tracking-progress"><div class="tracking-point done"><i></i><span>Booked</span></div><div class="tracking-line ${/dispatch|transit|loaded|deliver/i.test(s.status)?'done':''}"></div><div class="tracking-point ${/dispatch|transit|loaded|deliver/i.test(s.status)?'done':''}"><i></i><span>In Transit</span></div><div class="tracking-line ${delivered(s.status)?'done':''}"></div><div class="tracking-point ${delivered(s.status)?'done':''}"><i></i><span>Delivered</span></div></div><div class="detail-grid"><div><span>Status</span><strong>${esc(s.status)}</strong></div><div><span>Equipment</span><strong>${esc(s.equipment_type||'—')}</strong></div><div><span>Pickup</span><strong>${esc(fmtDateTime(s.picked_up_at||s.pickup_scheduled_at))}</strong></div><div><span>Delivery</span><strong>${esc(fmtDateTime(s.delivered_at||s.delivery_scheduled_at))}</strong></div><div><span>Commodity</span><strong>${esc(s.commodity||'—')}</strong></div><div><span>Customer Ref</span><strong>${esc(s.customer_reference||'—')}</strong></div>${s.customer_rate!==null&&s.customer_rate!==undefined?`<div><span>Rate</span><strong>${esc(money(s.customer_rate))}</strong></div>`:''}<div><span>Documents</span><strong>${docs.length}</strong></div></div>${s.public_notes?`<div class="customer-note"><b>Blue Logistics update</b><p>${esc(s.public_notes)}</p></div>`:''}${s.exception_note?`<div class="exception-box"><b>⚠ Shipment exception</b><p>${esc(s.exception_note)}</p></div>`:''}${s.tracking_url?`<a class="btn primary tracking-link" target="_blank" rel="noopener" href="${esc(s.tracking_url)}">Open Connected Carrier Tracking →</a>`:''}<div class="timeline"><div class="portal-panel-head"><div><span class="portal-kicker">TRACKING TIMELINE</span><h3>Milestone history</h3></div><small>${latest?`Latest ${esc(fmtDateTime(latest.occurred_at))}`:''}</small></div>${events.length?events.map((e,i)=>`<div class="timeline-row ${i===0?'latest':''}"><div class="timeline-dot"></div><div><div class="timeline-top"><strong>${esc(e.title)}</strong><time>${esc(fmtDateTime(e.occurred_at))}</time></div><p>${esc(e.details||e.status||'Shipment milestone updated.')}</p>${e.location?`<small>📍 ${esc(e.location)}</small>`:''}</div></div>`).join(''):`<div class="portal-empty small"><p>No milestone events have been posted yet.</p></div>`}</div>`}

function buildDocumentFilter(){const sel=$('documentFilter'),value=sel.value||'all';sel.innerHTML='<option value="all">All documents</option>'+companyShipments().map(s=>`<option value="${esc(s.id)}">${esc(s.reference_number)} · ${esc(s.origin)} → ${esc(s.destination)}</option>`).join('');if([...sel.options].some(o=>o.value===value))sel.value=value}
function docIcon(type='',mime=''){const x=`${type} ${mime}`.toLowerCase();if(x.includes('pod'))return'✅';if(x.includes('bol'))return'📋';if(x.includes('invoice'))return'💵';if(x.includes('rate'))return'💲';if(x.includes('image'))return'🖼️';return'📄'}
function renderDocuments(){const filter=$('documentFilter').value||'all';let docs=companyDocs();if(filter!=='all')docs=docs.filter(d=>d.shipment_id===filter);const list=$('documentList');if(!docs.length){list.innerHTML=`<div class="portal-empty small"><span>📄</span><p>No customer documents are available for this selection.</p></div>`;return}list.innerHTML=docs.map(d=>`<article class="document-row"><div class="doc-icon">${docIcon(d.document_type,d.mime_type)}</div><div><strong>${esc(d.original_name)}</strong><span>${esc(d.document_type)}${d.size_bytes?` • ${esc(size(d.size_bytes))}`:''}</span></div><button data-doc="${esc(d.id)}">Open Securely →</button></article>`).join('');list.querySelectorAll('[data-doc]').forEach(btn=>btn.addEventListener('click',async()=>{const original=btn.textContent;btn.disabled=true;btn.textContent='Opening…';try{const data=await api('document',{id:btn.dataset.doc});window.open(data.url,'_blank','noopener,noreferrer')}catch(err){showNotice(err.message||'Unable to open document.','error')}finally{btn.disabled=false;btn.textContent=original}}))}

function renderQuotes(){const quotes=companyQuotes(),list=$('quoteList');if(!quotes.length){list.innerHTML=`<div class="portal-empty small"><span>💲</span><p>No recent quote records are linked to this customer account.</p></div>`;return}list.innerHTML=quotes.slice(0,15).map(q=>`<article class="quote-row"><div><strong>${esc(q.quote_number||'Quote')}</strong><span>${esc(q.origin||'Origin')} → ${esc(q.destination||'Destination')}</span></div><div><b>${esc(money(q.customer_rate))}</b><span class="status-pill ${statusClass(q.status)}">${esc(q.status||'Quote')}</span></div></article>`).join('')}

client.auth.onAuthStateChange((event,session)=>{if(event==='SIGNED_IN'&&session)loadPortal();if(event==='SIGNED_OUT'){app.hidden=true;login.hidden=false}});
(async()=>{const session=await getSession();if(session)await loadPortal();else{login.hidden=false;app.hidden=true}})();
setInterval(async()=>{if(await getSession())loadPortal(false)},60000);
