if(!document.querySelector('link[href*="easy-customer.css"]')){const ec=document.createElement('link');ec.rel='stylesheet';ec.href='easy-customer.css?v=20260901-6';document.head.appendChild(ec)}
const m=document.querySelector('.menu'),n=document.querySelector('.navlinks');m?.addEventListener('click',()=>n.classList.toggle('open'));document.querySelectorAll('.navlinks a').forEach(a=>a.addEventListener('click',()=>n.classList.remove('open')));const y=document.getElementById('year');if(y)y.textContent=new Date().getFullYear();

if(n&&!n.querySelector('a[href="portal.html"]')){const portal=document.createElement('a');portal.href='portal.html';portal.textContent='Customer Portal';const quote=n.querySelector('.cta-nav');n.insertBefore(portal,quote||null);portal.addEventListener('click',()=>n.classList.remove('open'))}
const connect=document.querySelector('footer .footer-grid>div:last-child');if(connect&&!connect.querySelector('a[href="portal.html"]')){const portalFoot=document.createElement('a');portalFoot.href='portal.html';portalFoot.textContent='Customer Portal';connect.prepend(portalFoot)}

if(!document.querySelector('.mobile-quote')){
 const mobileQuote=document.createElement('a');
 mobileQuote.className='mobile-quote';mobileQuote.href='contact.html#quote';mobileQuote.textContent='Request a Freight Quote →';mobileQuote.setAttribute('aria-label','Request a freight quote');
 document.body.appendChild(mobileQuote);
}

if(document.body.classList.contains('home-v2')){
 const heroCopy=document.querySelector('.hero-copy');
 if(heroCopy&&!heroCopy.querySelector('.hero-proof-row')){
  const proof=document.createElement('div');proof.className='hero-proof-row';
  proof.innerHTML='<a class="hero-rating-badge" target="_blank" rel="noopener" href="https://g.page/r/CbO6Az7x38l3EBM"><span class="hero-rating-stars">★★★★★</span><strong>4.9 Google Rating</strong><small>49 public reviews</small></a><a class="hero-track-btn" href="portal.html"><span>⌖</span><div><strong>Track Shipment</strong><small>Open Customer Portal</small></div></a>';
  const benefits=heroCopy.querySelector('.hero-benefits');(benefits||heroCopy).insertAdjacentElement('afterend',proof);
 }
 const trust=document.querySelector('.trust-band-v2');
 if(trust&&!document.querySelector('.freight-choice-section')){
  const chooser=document.createElement('section');chooser.className='freight-choice-section';chooser.innerHTML='<div class="container"><div class="freight-choice-head"><span>NOT SURE WHAT TO CALL IT?</span><h2>Choose what sounds closest.</h2><p>You do not need to know freight terminology. Pick the closest option and Blue Logistics can help with the rest.</p></div><div class="freight-choice-grid"><button type="button" data-quote-service="LTL"><b>1–6 pallets</b><strong>Smaller freight</strong><small>Usually LTL</small></button><button type="button" data-quote-service="FTL"><b>Large shipment</b><strong>Full truck</strong><small>Usually FTL</small></button><button type="button" data-quote-service="Imports"><b>Port / container</b><strong>Import freight</strong><small>Inland transportation</small></button><button type="button" data-quote-service="Warehousing"><b>Need storage</b><strong>Warehousing</strong><small>Storage + distribution</small></button><button type="button" data-quote-service="Other" class="freight-choice-other"><b>I am not sure</b><strong>Help me choose</strong><small>We will figure it out together</small></button></div></div>';
  trust.insertAdjacentElement('afterend',chooser);
  chooser.querySelectorAll('[data-quote-service]').forEach(btn=>btn.addEventListener('click',()=>{const form=document.getElementById('quoteForm'),service=form?.elements.namedItem('service');if(service)service.value=btn.dataset.quoteService||'Other';form?.scrollIntoView({behavior:'smooth',block:'center'});setTimeout(()=>form?.querySelector('[name="pickup_location"]')?.focus(),500)}));
 }
 const capability=document.querySelector('.capability-showcase');
 if(capability&&!document.querySelector('.case-study-showcase')){
  const cases=document.createElement('section');cases.className='section case-study-showcase';
  cases.innerHTML='<div class="container"><div class="section-head center"><span>SHIPMENT EXAMPLES</span><h2>How we approach real freight problems.</h2><p>Illustrative examples of the type of transportation challenges Blue Logistics is built to support. Customer names and private shipment details are not published without approval.</p></div><div class="case-study-grid"><article class="case-study-card"><div class="case-route">NC → TX</div><span>FTL DRY VAN • TIME-SENSITIVE</span><h3>Urgent capacity without losing communication.</h3><p><b>Challenge:</b> A shipment needs dependable truckload coverage on a compressed pickup window.</p><p><b>Blue approach:</b> Match the lane to the right equipment, communicate changes quickly, and stay engaged through delivery.</p><small>Representative capability example</small></article><article class="case-study-card"><div class="case-route">PORT → WAREHOUSE</div><span>IMPORT • INLAND TRANSPORT</span><h3>Connecting inbound cargo to the next destination.</h3><p><b>Challenge:</b> Imported freight needs coordinated pickup, inland transport and a warehouse handoff.</p><p><b>Blue approach:</b> Coordinate the transportation pieces through one responsive point of contact.</p><small>Representative capability example</small></article><article class="case-study-card"><div class="case-route">MULTI-LANE</div><span>LTL + FTL • RECURRING SUPPORT</span><h3>One contact for multiple freight needs.</h3><p><b>Challenge:</b> A shipper has recurring lanes using different modes and timing requirements.</p><p><b>Blue approach:</b> Centralize quoting, shipment coordination and follow-through across the account.</p><small>Representative capability example</small></article></div><div class="case-study-actions"><a class="btn primary" href="contact.html#quote">Talk Through Your Shipment →</a><a class="btn outline dark-outline" href="portal.html">Track an Existing Shipment →</a></div></div>';
  capability.insertAdjacentElement('afterend',cases);
 }
 const cta=document.querySelector('.cta-strip-v2');
 if(cta&&!document.querySelector('.customer-faq')){
  const faq=document.createElement('section');faq.className='customer-faq';faq.innerHTML='<div class="container"><div class="section-head center"><span>QUICK ANSWERS</span><h2>Freight does not have to be complicated.</h2></div><div class="customer-faq-grid"><details open><summary>What information do I need for a quote?</summary><p>Pickup location, delivery location, what you are shipping, approximate weight and when it needs to move. If you do not know every detail yet, send what you have.</p></details><details><summary>What if I do not know whether it is LTL or FTL?</summary><p>That is fine. Choose “Help me choose” or the closest option. Blue Logistics can help determine the right mode and equipment.</p></details><details><summary>Can I track a shipment online?</summary><p>Yes. Use the Customer Portal or the Track button on the website to view available shipment information and documents.</p></details><details><summary>Do I need an account before requesting a quote?</summary><p>No. The website quote wizard is designed so a new customer can request pricing without creating an account first.</p></details></div></div>';
  cta.insertAdjacentElement('beforebegin',faq);
 }
 if(!document.querySelector('.desktop-help-pill')){const help=document.createElement('a');help.className='desktop-help-pill';help.href='mailto:hmblue@bluelogisticsllc.us?subject=Website%20Freight%20Help';help.innerHTML='<span>?</span><div><strong>Need help?</strong><small>Email Blue Logistics</small></div>';document.body.appendChild(help)}
}

if(document.body.classList.contains('service-page')){
 const ph=document.querySelector('.pagehero');
 if(ph&&!document.querySelector('.service-proof-bar')){
  const bar=document.createElement('section');bar.className='service-proof-bar';bar.innerHTML='<div class="container service-proof-grid"><div><strong>Authorized Freight Broker</strong><small>MC 1689495</small></div><div><strong>4.9 Google Rating</strong><small>49 public reviews</small></div><div><strong>Nationwide Support</strong><small>LTL • FTL • Imports • Storage</small></div><div><strong>Customer Portal</strong><small>Tracking + documents</small></div></div>';ph.insertAdjacentElement('afterend',bar);
 }
 const firstHead=document.querySelector('.service-page main .section-head');
 if(firstHead&&!firstHead.querySelector('.service-mini-actions')){
  const acts=document.createElement('div');acts.className='service-mini-actions';acts.innerHTML='<a class="btn primary" href="contact.html#quote">Request a Quote →</a><a class="btn portal-link" href="portal.html">Track Shipment / Portal →</a>';firstHead.appendChild(acts);
 }
}

const quoteForm=document.getElementById('quoteForm');
if(quoteForm){
 if(document.body.classList.contains('home-v2')&&!quoteForm.dataset.wizardReady){
  quoteForm.dataset.wizardReady='true';
  const fields={
   first:quoteForm.querySelector('[name="first_name"]')?.closest('label'),last:quoteForm.querySelector('[name="last_name"]')?.closest('label'),email:quoteForm.querySelector('[name="email"]')?.closest('label'),origin:quoteForm.querySelector('[name="pickup_location"]')?.closest('label'),destination:quoteForm.querySelector('[name="delivery_location"]')?.closest('label'),service:quoteForm.querySelector('[name="service"]')?.closest('label'),weight:quoteForm.querySelector('[name="weight"]')?.closest('label'),date:quoteForm.querySelector('[name="pickup_date"]')?.closest('label')
  };
  const status=quoteForm.querySelector('#quoteStatus'),submit=quoteForm.querySelector('#quoteSubmit'),repeat=quoteForm.querySelector('#repeatQuote'),note=quoteForm.querySelector('.hero-form-note');
  const oldRows=[...quoteForm.querySelectorAll('.hero-form-row')];oldRows.forEach(r=>{[...r.children].forEach(c=>quoteForm.insertBefore(c,r));r.remove()});
  const title=quoteForm.querySelector('h2');if(title)title.textContent='Get My Freight Quote';const kicker=quoteForm.querySelector('.quote-kicker');if(kicker)kicker.textContent='FAST • SIMPLE • SECURE';
  const progress=document.createElement('div');progress.className='quote-wizard-progress';progress.innerHTML='<button type="button" data-step-dot="1"><b>1</b><span>Lane</span></button><i></i><button type="button" data-step-dot="2"><b>2</b><span>Freight</span></button><i></i><button type="button" data-step-dot="3"><b>3</b><span>Contact</span></button>';title?.insertAdjacentElement('afterend',progress);
  const intro=document.createElement('p');intro.className='quote-wizard-intro';intro.textContent='Answer a few quick questions. No account required.';progress.insertAdjacentElement('afterend',intro);
  const makeStep=(num,heading,sub)=>{const s=document.createElement('section');s.className='quote-wizard-step';s.dataset.step=String(num);s.innerHTML=`<div class="quote-step-heading"><span>STEP ${num} OF 3</span><h3>${heading}</h3><p>${sub}</p></div>`;return s};
  const s1=makeStep(1,'Where is it going?','Start with the pickup and delivery locations.');const laneRow=document.createElement('div');laneRow.className='hero-form-row';fields.origin&&laneRow.append(fields.origin);fields.destination&&laneRow.append(fields.destination);s1.append(laneRow);fields.date&&s1.append(fields.date);
  const s2=makeStep(2,'What are you shipping?','Choose the closest freight type. You can keep it simple.');const freightRow=document.createElement('div');freightRow.className='hero-form-row';fields.service&&freightRow.append(fields.service);fields.weight&&freightRow.append(fields.weight);s2.append(freightRow);const optional=document.createElement('div');optional.className='quote-wizard-help';optional.innerHTML='<span>Not sure?</span> Pick <b>Other</b> and our team will help determine the right equipment.';s2.append(optional);
  const s3=makeStep(3,'How can we reach you?','We’ll use this only to respond to your freight request.');const nameRow=document.createElement('div');nameRow.className='hero-form-row';fields.first&&nameRow.append(fields.first);fields.last&&nameRow.append(fields.last);s3.append(nameRow);fields.email&&s3.append(fields.email);
  const controls=document.createElement('div');controls.className='quote-wizard-controls';controls.innerHTML='<button type="button" class="quote-back">← Back</button><button type="button" class="btn primary quote-next">Next →</button>';quoteForm.insertBefore(s1,status);quoteForm.insertBefore(s2,status);quoteForm.insertBefore(s3,status);quoteForm.insertBefore(controls,status);
  let step=1;const stepEls=[s1,s2,s3],dots=[...progress.querySelectorAll('[data-step-dot]')],back=controls.querySelector('.quote-back'),next=controls.querySelector('.quote-next');const requiredByStep={1:['pickup_location','delivery_location'],2:['service'],3:['first_name','last_name','email']};
  const showStep=(num)=>{step=Math.max(1,Math.min(3,num));stepEls.forEach((el,i)=>el.classList.toggle('active',i===step-1));dots.forEach((d,i)=>{d.classList.toggle('active',i===step-1);d.classList.toggle('done',i<step-1)});back.style.visibility=step===1?'hidden':'visible';next.hidden=step===3;submit.hidden=step!==3;if(note)note.hidden=step!==3;if(repeat&&!repeat.hidden)repeat.hidden=step!==3;intro.textContent=step===1?'Answer a few quick questions. No account required.':step===2?'You’re halfway there. Basic freight details are enough.':'Last step — tell us where to send the quote.'};
  const validateStep=()=>{for(const name of requiredByStep[step]){const el=quoteForm.elements.namedItem(name);if(el&&!el.checkValidity()){el.reportValidity();return false}}return true};next.addEventListener('click',()=>{if(validateStep())showStep(step+1)});back.addEventListener('click',()=>showStep(step-1));dots.forEach(d=>d.addEventListener('click',()=>{const target=Number(d.dataset.stepDot);if(target<step)showStep(target)}));quoteForm.addEventListener('reset',()=>setTimeout(()=>showStep(1),0));showStep(1);
 }
 const quoteSubmit=document.getElementById('quoteSubmit'),quoteStatus=document.getElementById('quoteStatus'),repeatQuote=document.getElementById('repeatQuote'),attachments=document.getElementById('quoteAttachments');let lastQuoteData=null,isRepeat=false;const params=new URLSearchParams(location.search),trackingKeys=['utm_source','utm_medium','utm_campaign','utm_content','utm_term','gclid','fbclid'];const detectedSource=()=>params.get('utm_source')||(document.referrer.includes('google')?'google':document.referrer.includes('instagram')?'instagram':document.referrer.includes('linkedin')?'linkedin':document.referrer.includes('facebook')?'facebook':document.referrer?'referral':'direct');let attribution={source_detail:detectedSource(),landing_page:location.href,referrer:document.referrer};trackingKeys.forEach(k=>{if(params.get(k))attribution[k]=params.get(k)});try{const saved=sessionStorage.getItem('blue_quote_attribution');if(saved)attribution={...JSON.parse(saved),...attribution};else sessionStorage.setItem('blue_quote_attribution',JSON.stringify(attribution))}catch{}
 repeatQuote?.addEventListener('click',()=>{if(!lastQuoteData)return;Object.entries(lastQuoteData).forEach(([name,value])=>{const field=quoteForm.elements.namedItem(name);if(field&&field.type!=='file'&&field.type!=='checkbox')field.value=value});isRepeat=true;repeatQuote.hidden=true;quoteStatus.textContent='Similar shipment details restored. Update the lane, date, or freight details before submitting.';quoteStatus.style.color='#0872df';quoteForm.scrollIntoView({behavior:'smooth',block:'start'})});
 quoteForm.addEventListener('submit',async e=>{e.preventDefault();if(!quoteForm.checkValidity()){quoteForm.reportValidity();return;}const files=Array.from(attachments?.files||[]);if(files.length>3||files.some(file=>file.size>10*1024*1024)){quoteStatus.textContent='Attach no more than 3 files, 10 MB or less each.';quoteStatus.style.color='#c53535';return;}const smsOpt=quoteForm.elements.namedItem('sms_opt_in');if(smsOpt?.checked&&!quoteForm.elements.namedItem('phone')?.value.trim()){quoteStatus.textContent='Enter a phone number to receive text confirmation.';quoteStatus.style.color='#c53535';return;}const formData=new FormData(quoteForm);Object.entries(attribution).forEach(([key,value])=>formData.set(key,String(value||'')));formData.set('repeat_request',String(isRepeat));lastQuoteData=Object.fromEntries(Array.from(formData.entries()).filter(([,value])=>typeof value==='string'&&value));quoteSubmit.disabled=true;quoteSubmit.textContent='Sending quote request…';quoteStatus.textContent='Sending securely to Blue Logistics…';quoteStatus.style.color='#8ecbff';const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),15000);try{const r=await fetch(`https://scrbdfwpthsylmhtqjeu.supabase.co/functions/v1/public-quote-intake?t=${Date.now()}`,{method:'POST',headers:{'Accept':'application/json'},body:formData,cache:'no-store',signal:controller.signal});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||'Unable to submit quote request.');if(!data.ok||!data.request_id)throw new Error('The server did not confirm a quote reference. Please retry.');quoteForm.reset();isRepeat=false;repeatQuote.hidden=false;const smsNote=data.sms_status==='sent'?' Text confirmation sent.':data.sms_status==='not_configured'?' Text confirmation is not active yet; your quote was still received.':'';const fileNote=Number(data.attachment_count)>0?` ${data.attachment_count} document${Number(data.attachment_count)>1?'s':''} secured.`:'';quoteStatus.textContent=`✓ Quote request received. Reference ${String(data.request_id).slice(0,8).toUpperCase()}.${fileNote}${smsNote} Blue Logistics has the request${Number(data.push_sent)>0?' and the owner alert was sent':''}.`;quoteStatus.style.color='#18794e';quoteSubmit.textContent='Quote Request Sent ✓';setTimeout(()=>{quoteSubmit.disabled=false;quoteSubmit.textContent='Request My Freight Quote →'},3500);}catch(err){quoteStatus.textContent=`We couldn't confirm the quote request. ${err?.name==='AbortError'?'The request timed out.':(err.message||'')} Please try again or email hmblue@bluelogisticsllc.us.`;quoteStatus.style.color='#ff9b9b';quoteSubmit.disabled=false;quoteSubmit.textContent='Try Again →';}finally{clearTimeout(timer)}});
}
